image: gitpod/workspace-node-lts

ports:
  - port: 3000
    onOpen: open-preview
    visibility: public

tasks:
  - name: Start MongoDB and app
    init: |
      sudo service mongodb start
      npm install
    command: npm run start
