# .gitpod.yml
image: gitpod/workspace-node-lts

ports:
  - port: 3000
    onOpen: open-preview
    visibility: public
  - port: 27017
    visibility: private

tasks:
  - name: Start MongoDB and app
    init: |
      docker-compose up -d
      npm install
    command: npm run start

vscode:
  extensions:
    - https://github.com/freeCodeCamp/freecodecamp-dark-vscode-theme/releases/download/v1.0.0/freecodecamp-dark-vscode-theme-1.0.0.vsix